// tailwind.config.cjs
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx,html}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Backwards compatibility
        navy: '#0a0f2c',
        cyan: '#00f0ff',
        grayLight: '#cbd5e1',

        // Spectra / Obsidian Forge design system
        primary: '#80ffed',
        'on-primary': '#003732',
        'primary-container': '#20e6d2',
        'on-primary-container': '#006359',
        'primary-fixed': '#48fbe7',
        'primary-fixed-dim': '#00decb',
        'on-primary-fixed': '#00201c',
        'on-primary-fixed-variant': '#005048',
        'inverse-primary': '#006a60',

        background: '#0e131e',
        'on-background': '#dee2f2',
        surface: '#0e131e',
        'surface-dim': '#0e131e',
        'surface-bright': '#343946',
        'surface-variant': '#303541',
        'surface-tint': '#00decb',
        'surface-container-lowest': '#090e19',
        'surface-container-low': '#161b27',
        'surface-container': '#1b1f2b',
        'surface-container-high': '#252a36',
        'surface-container-highest': '#303541',
        'on-surface': '#dee2f2',
        'on-surface-variant': '#bacac6',
        'inverse-surface': '#dee2f2',
        'inverse-on-surface': '#2b303d',

        outline: '#849490',
        'outline-variant': '#3b4a47',

        secondary: '#bdc7de',
        'on-secondary': '#273142',
        'secondary-container': '#3d475a',
        'on-secondary-container': '#abb5cc',
        'secondary-fixed': '#d9e3fa',
        'secondary-fixed-dim': '#bdc7de',
        'on-secondary-fixed': '#121c2d',
        'on-secondary-fixed-variant': '#3d475a',

        tertiary: '#8fffd1',
        'on-tertiary': '#003827',
        'tertiary-container': '#4be6b1',
        'on-tertiary-container': '#006448',
        'tertiary-fixed': '#65fcc5',
        'tertiary-fixed-dim': '#41dfaa',
        'on-tertiary-fixed': '#002115',
        'on-tertiary-fixed-variant': '#00513a',

        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        margin: '2.5rem',
        'margin-mobile': '1.25rem',
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
      },
      fontFamily: {
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-xl': ['Space Grotesk', 'sans-serif'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'display-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'body-sm': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-sm': ['Hanken Grotesk', 'sans-serif'],
        'label-md': ['Hanken Grotesk', 'sans-serif'],
        'mono-code': ['Space Mono', 'monospace'],
        'mono-badge': ['Space Mono', 'monospace'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'body-lg': ['17px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '0em', fontWeight: '500' }],
        'headline-md': ['22px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '500' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'mono-code': ['12px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'mono-badge': ['10px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
